# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spread-Message
version:      0.21
version_from: Message.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Spread:                        0
    Sys::Hostname:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
